# Generated by Django 5.0.2 on 2025-08-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bitcoin_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='bitcoin_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='bitcoin_txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='voucher_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash Deposit'), ('card', 'Card Payment'), ('bitcoin', 'Bitcoin'), ('voucher', 'Voucher')], max_length=20),
        ),
    ]
