# Generated by Django 5.0.2 on 2025-08-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investmentplan_planinvestment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referralreward',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deposit'),
        ),
    ]
