# Generated by Django 5.0.14 on 2025-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_lead_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='funds_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
