# Generated by Django 5.0.2 on 2025-10-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_investment_funds_claimed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
