# Generated by Django 5.0.2 on 2026-02-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_bot_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFTBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
