# Generated by Django 5.0.2 on 2026-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'No Admin Role'), ('super_admin', 'Super Admin'), ('finance_admin', 'Finance Admin'), ('user_admin', 'User Admin'), ('marketing_admin', 'Marketing Admin'), ('content_admin', 'Content Admin')], help_text='Role-based access control for admin dashboard sections', max_length=50, null=True),
        ),
    ]
