# Generated by Django 5.0.2 on 2026-08-01 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_admin_role_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='duration_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash Send')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
