# Generated by Django 5.0.2 on 2026-08-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_support_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planinvestment',
            unique_together=set(),
        ),
    ]
